### ISSUE TITLE
Problem installing 2.0.3 from conda

### ISSUE THREAD

**Issue by BCSK93** [patonlab/GoodVibes#21]
Hi,

I've tried using conda to install GoodVibes with the command 'conda install -c patonlab goodvibesand' but couldn't get it to work as described in the documentation. 

The following shown up:

Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - goodvibes

Current channels:

  - https://conda.anaconda.org/patonlab/win-64
  - https://conda.anaconda.org/patonlab/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

If I tried with 'pip install goodvibes' it successfully installed but cant run any file.

It showed the following:

(base) PS>python -m goodvibes -h
Usage: __main__.py [options] <input1>.log <input2>.log ...

Options:
  -h, --help        show this help message and exit
  -t TEMP           temperature (K) (default 298.15)
  -q QH             Type of quasi-harmonic correction (Grimme or Truhlar)
                    (default Grimme)
  -f FREQ_CUTOFF    Cut-off frequency (wavenumbers) (default = 100)
  -c CONC           concentration (mol/l) (default 1 atm)
  -v SCALE_FACTOR   Frequency scaling factor (default 1)
  -s SOLV           Solvent (H2O, toluene, DMF, AcOH, chloroform) (default
                    none)
  --spc=SPC         Indicates single point corrections (default False)
  --boltz           Show Boltzmann factors
  --cpu             Total CPU time
  --ti=TI           initial temp, final temp, step size (K)
  --ci=CI           initial conc, final conc, step size (mol/l)
  --xyz             write Cartesians to an xyz file (default False)
  --imag            print imaginary frequencies (default False)
  --cosmo=COSMO-RS  filename of a COSMO-RS out file
  --csv             print CSV format
(base) PS>python -m goodvibes examples/methylaniline.out -f 100
   GoodVibes v2.0.2 2019/06/28 09:16:53
   REF: Funes-Ardoiz, I.; Paton, R. S. (2016). GoodVibes: GoodVibes 2.0.2 http://doi.org/10.5281/zenodo.595246
   Requested: -f 100

   Temperature = 298.15 Kelvin   Pressure = 1 atmTraceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Miniconda2\lib\site-packages\goodvibes\__main__.py", line 18, in <module>
    sys.exit(GoodVibes.main())
  File "C:\ProgramData\Miniconda2\lib\site-packages\goodvibes\GoodVibes.py", line 556, in main
    if l_o_t[0].upper() == scal['level'].upper() or l_o_t[0].upper() == scal['level'].replace("-","").upper():
IndexError: list index out of range

I'm using python2.7 in windows

Any solution?

Thanks,
Bowie

**Comment by bobbypaton** [comment]
Regarding the conda installation, currently only the OSX version is available. In the next 1-2 weeks there will be an updated version of goodvibes and we will make sure that this is addressed.

Regarding the pip installation - it looks like everything has been installed correctly! 
In order to test out the examples, you will also have to download the examples folder onto your local machine (you can download the zipped repository from GitHub and the folder will be inside there). Your current error is because the file examples/methylaniline.out is not in your current working directory. You could always just repeat the examples using one of your own Gaussian output files to hand. For example if you are in a directory with the file "output.log" or "output.out", then you can just run the code as "python -m goodvibes output.log" followed by the options specified in the examples ...

**Comment by BCSK93** [comment]
Thanks for the reply. I got it up and running now.
