### ISSUE TITLE
Ssym gives different G with C1

### ISSUE THREAD

**Issue by dking072** [patonlab/GoodVibes#34]
Hello,

I am using GoodVibes to calculate the quasiharmonic Gibbs free energy of some rather large molecules that are definitely C1. I have experimented with the use of the --ssym option, because there are smaller molecules in the project that do have symmetry. However, when I use the --ssym option on my C1 molecules I appear to get different results. For example, on one particular complex I have:

python -m goodvibes --qs truhlar -t 373.15 -v 0.976 --imag *.out
Corrected G: -4939.567977

python -m goodvibes --qs truhlar -t 373.15 -v 0.976 --ssym --imag *.out
Corrected G: -4939.565380

The program appears to properly identify the molecules as C1, so I don't think I should be getting a difference between the two values, unless I am mistaken.

Thank you for your excellent program.

**Comment by luchini18** [comment]
Hi,
Thanks for the submission, this difference you are seeing is coming from the internal symmetry term of the molecule. This term is often used in terms for treating free rotor entropies and since we are employing either Truhlar or Grimme-type corrections to take care of these low-frequency modes, the effect of this internal symmetry term has been effectively eliminated in the most recent update, so you should see no symmetry correction for C1 molecules.
